# Generated by Django 3.0.7 on 2021-03-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0002_auto_20210331_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='hostingProvider',
        ),
        migrations.RemoveField(
            model_name='quoteinputmodel',
            name='location',
        ),
        migrations.CreateModel(
            name='HostingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54)),
                ('hostingProvider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.HostingProvider')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.Location')),
            ],
        ),
    ]
