# Generated by Django 3.0.7 on 2021-03-31 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0003_auto_20210331_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteinputmodel',
            name='hostingProvider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.HostingProvider'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoteInput.Location'),
        ),
        migrations.AddField(
            model_name='quoteinputmodel',
            name='name',
            field=models.CharField(max_length=54, null=True),
        ),
    ]
