# Generated by Django 3.0.7 on 2021-03-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteInput', '0004_auto_20210331_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostingModel',
        ),
    ]
