# Generated by Django 2.2.6 on 2020-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPSCalc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRPlanningLaborCostRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRPlanningLaborCostRate_USDPerHr', models.IntegerField(max_length=26)),
            ],
        ),
    ]
